swagger: "2.0"
info:
  description: "This is the Swagger API Documentation for Featured Location Web Application"
  version: "1.0.0"
  title: "Featured Location"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pramodreddy096@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "maryville-guide.herokuapp.com"
basePath: "/api"
tags:
- name: "user"
  description: "User Login Credentials"
- name: "location"
  description: "Details of All the Locations"

schemes:
- "https"

paths:
  /users:
    get:
      tags:
      - "user"
      summary: "Get a list of all the users"
      description: ""
      operationId: "getUsers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "405":
          description: "Invalid input"

    post:
      tags:
      - "user"
      summary: "Add user login credentials"
      description: ""
      operationId: "postUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userName"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "email"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: ""
        required: true
        type: "string"    
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/user"
        "400":
          description: "Invalid status value"


  /locations:
    get:
      tags:
      - "location"
      summary: "Get a list of all the Locations"
      description: ""
      operationId: "getLocations"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "405":
          description: "Invalid input"

    post:
      tags:
      - "location"
      summary: "Add a Location"
      description: ""
      operationId: "postLocation"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "locationName"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "address"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "hours"
        in: "query"
        description: ""
        required: true
        type: "string" 
      - name: "phoneNumber"
        in: "query"
        description: ""
        required: true
        type: "string" 
      - name: "photo"
        in: "query"
        description: ""
        required: true
        type: "string" 
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/location"
        "400":
          description: "Invalid status value"


definitions:
  user:
    type: "object"
    properties:
      userName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"

  location:
    type: "object"
    properties:
      locationName:
        type: "string"
      address:
        type: "string"
      hours:
        type: "string"
      phoneNumber:
        type: "string"
      photo:
        type: "string"

 
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"